### PR TITLE
added support for Font Family to link generation and config

### PR DESCRIPTION
**Pull request by emlazzarin**
These changes add support for specifying a Font Family. Let me know if this looks right, or if there are any supporting changes you think are necessary.

### CODE REVIEW

**Comment by gh640** [comment]
I checked the PR and it works well in my environment. It looks good me but it'd be better if the README is changed.

**Comment by emlazzarin** [comment]
What would you like changed? I did edit the `README`.

**Comment by gh640** [comment]
@emlazzarin I'm sory. I don't remember how but I misunderstood the changes... It works well and I merged it. Thanks :)

@molnarmark in the case you don't think it's good, please feel free to revert it.

**Comment by gh640** [comment]
I tagged the latest HEAD with `1.2.1` for a newer version.

**Pull request merged**
